yarnPath: ".yarn/releases/yarn-berry.cjs"
nodeLinker: "node-modules"
packageExtensions:
  deasync@*:
     dependencies:
        node-gyp: ^8.2.0
checksumBehavior: "update"
enableImmutableInstalls: false
