approvedGitRepositories:
  - "**"

checksumBehavior: update

compressionLevel: mixed

enableGlobalCache: false

enableImmutableInstalls: false

enableScripts: true

nodeLinker: node-modules

packageExtensions:
  deasync@*:
    dependencies:
      node-gyp: ^8.2.0

yarnPath: .yarn/releases/yarn-4.14.1.cjs
