approvedGitRepositories:
  - "**"

checksumBehavior: update

compressionLevel: mixed

enableGlobalCache: false

enableImmutableInstalls: false

enableScripts: true

nodeLinker: node-modules

npmMinimalAgeGate: 0

packageExtensions:
  deasync@*:
    dependencies:
      node-gyp: ^8.2.0

yarnPath: .yarn/releases/yarn-4.18.0.cjs
