(function () {
    'use strict';

    angular
        .module('chpl', [
            'angular-confirm',
            'angular-loading-bar',
            'angulartics',
            'angulartics.google.tagmanager',
            'chpl.admin',
            'chpl.charts',
            'chpl.chpl_api',
            'chpl.cms_lookup',
            'chpl.collections',
            'chpl.compare',
            'chpl.components',
            'chpl.constants',
            'chpl.download',
            'chpl.navigation',
            'chpl.overview',
            'chpl.product',
            'chpl.registration',
            'chpl.search',
            'chpl.services',
            'googlechart',
            'ngAnimate',
            'ngAria',
            'ngCsv',
            'ngCytoscape',
            'ngMessages',
            'ngResource',
            'ngRoute',
            'ngSanitize',
            'ngTouch',
            'swaggerUi',
            'toaster',
            'ui.bootstrap',
            'ui.bootstrap.fontawesome',
        ]);
})();
