import { compareBoolean, compareObject, comparePrimitive } from 'pages/reports/reports.v2.service';
import { getDisplayDateFormat } from 'services/date-util';

const lookup = {
  shortCircuit: [
    'root.currentStatus.certificationBody',
    'root.developer',
    'root.details.form',
    'root.details.listing.developer',
    'root.details.listing.product',
    'root.details.listing.sed',
  ],
  'root.certificationBodies': { message: () => undefined },
  'root.currentStatus': { message: () => 'Current Status' },
  'root.currentStatus.actingUser': { message: () => undefined },
  'root.currentStatus.changeRequestStatusType': { message: () => 'Status' },
  'root.currentStatus.changeRequestStatusType.actingUser': { message: () => undefined },
  'root.currentStatus.changeRequestStatusType.id': { message: () => undefined },
  'root.currentStatus.changeRequestStatusType.name': { message: (before, after) => comparePrimitive(before, after, 'name', 'Status') },
  'root.currentStatus.changeRequestStatusType.userGroupName': { message: () => undefined },
  'root.currentStatus.comment': { message: (before, after) => comparePrimitive(before, after, 'comment', 'Comment') },
  'root.currentStatus.id': { message: () => undefined },
  'root.currentStatus.statusChangeDateTime': { message: () => undefined },
  'root.currentStatus.userGroupName': { message: () => undefined },
  'root.details': { message: () => 'Details' },
  'root.details.address': { message: () => 'Address' },
  'root.details.address.city': { message: (before, after) => comparePrimitive(before, after, 'city', 'City') },
  'root.details.address.country': { message: (before, after) => comparePrimitive(before, after, 'country', 'Country') },
  'root.details.address.line1': { message: (before, after) => comparePrimitive(before, after, 'line1', 'Street Line 1') },
  'root.details.address.line2': { message: (before, after) => comparePrimitive(before, after, 'line2', 'Street Line 2') },
  'root.details.address.state': { message: (before, after) => comparePrimitive(before, after, 'state', 'State') },
  'root.details.address.zipcode': { message: (before, after) => comparePrimitive(before, after, 'zipcode', 'Zipcode') },
  'root.details.contact': { message: () => 'Contact' },
  'root.details.contact.email': { message: (before, after) => comparePrimitive(before, after, 'email', 'Email') },
  'root.details.contact.fullName': { message: (before, after) => comparePrimitive(before, after, 'fullName', 'Full Name') },
  'root.details.contact.phoneNumber': { message: (before, after) => comparePrimitive(before, after, 'phoneNumber', 'Phone Number') },
  'root.details.listing': { message: () => 'Listing' },
  'root.details.listing.accessibilityStandards': { message: () => undefined },
  'root.details.listing.businessErrorMessages': { message: () => undefined },
  'root.details.listing.certificationEvents': { message: () => undefined },
  'root.details.listing.certificationResults': { message: () => undefined },
  'root.details.listing.chplProductNumberHistory': { message: () => undefined },
  'root.details.listing.cqmResults': { message: () => undefined },
  'root.details.listing.dataErrorMessages': { message: () => undefined },
  'root.details.listing.directReviews': { message: () => undefined },
  'root.details.listing.errorMessages': { message: () => undefined },
  'root.details.listing.ics.children': { message: () => undefined },
  'root.details.listing.ics.parents': { message: () => undefined },
  'root.details.listing.measures': { message: () => undefined },
  'root.details.listing.promotingInteroperabilityUserHistory': { message: () => undefined },
  'root.details.listing.qmsStandards': { message: () => undefined },
  'root.details.listing.rwtPlansCheckDate': { message: (before, after) => comparePrimitive(before, after, 'rwtPlansCheckDate', 'RWT Plans Check Date', getDisplayDateFormat) }, // maybe not necessary? Check on this after a PROD DB pull
  'root.details.listing.rwtPlansUrl': { message: (before, after) => comparePrimitive(before, after, 'rwtPlansUrl', 'RWT Plans URL') },
  'root.details.listing.rwtResultsCheckDate': { message: (before, after) => comparePrimitive(before, after, 'rwtResultsCheckDate', 'RWT Results Check Date', getDisplayDateFormat) }, // maybe not necessary? Check on this after a PROD DB pull
  'root.details.listing.rwtResultsUrl': { message: (before, after) => comparePrimitive(before, after, 'rwtResultsUrl', 'RWT Results URL') },
  'root.details.listing.surveillance': { message: () => undefined },
  'root.details.listing.targetedUsers': { message: () => undefined },
  'root.details.listing.testingLabs': { message: () => undefined },
  'root.details.listing.warningMessages': { message: () => undefined },
  'root.details.selfDeveloper': { message: (before, after) => compareBoolean(before, after, 'selfDeveloper', 'Self-developer') },
  'root.details.signature': { message: (before, after) => comparePrimitive(before, after, 'signature', 'Signature') },
  'root.details.signatureEmail': { message: (before, after) => comparePrimitive(before, after, 'signatureEmail', 'Signer\'s Email') },
  'root.details.url': { message: (before, after) => comparePrimitive(before, after, 'url', 'URL') },
  'root.details.website': { message: (before, after) => comparePrimitive(before, after, 'website', 'Website') },
  'root.statuses': { message: () => undefined },
};

const compareChangeRequest = (prev, curr) => compareObject(prev, curr, lookup);

export default compareChangeRequest;
