module.exports = [
  {
    file: '2015 edition products (xml)',
    definitionFileName: 'listingSchema.xsd',
    dataFileName: 'chpl-2015',
    fileExtension: 'xml',
    dfSize: '95000',
    dSize: '400000',
    days: '1',

  },
  {
    file: '2014 edition products (xml)',
    definitionFileName: 'listingSchema.xsd',
    dataFileName: 'chpl-2014',
    fileExtension: 'xml',
    dfSize: '95000',
    dSize: '570000',
    days: '92',
  },
  {
    file: '2011 edition products (xml)',
    definitionFileName: 'listingSchema.xsd',
    dataFileName: 'chpl-2011',
    fileExtension: 'xml',
    dfSize: '95000',
    dSize: '190000',
    days: '92',
  },
  {
    file: '2015 edition summary (csv)',
    definitionFileName: '2015 Listing CSV Data Dictionary.csv',
    dataFileName: 'chpl-2015',
    fileExtension: 'csv',
    dfSize: '14000',
    dSize: '900',
    days: '1',
    dfLines: 100,
    dLines: 1300,
  },
  {
    file: '2014 edition summary (csv)',
    definitionFileName: '2014 Listing CSV Data Dictionary.csv',
    dataFileName: 'chpl-2014',
    fileExtension: 'csv',
    dfSize: '9000',
    dSize: '2800',
    days: '92',
    dfLines: 85,
    dLines: 5250,
  },
  {
    file: 'Surveillance Activity',
    definitionFileName: 'Surveillance and Nonconformity CSV Data Dictionary.csv',
    dataFileName: 'surveillance-all',
    fileExtension: 'csv',
    dfSize: '7000',
    dSize: '900',
    days: '1',
    dfLines: 30,
    dLines: 1700,
  },
  {
    file: 'Surveillance Non-Conformities',
    definitionFileName: 'Surveillance and Nonconformity CSV Data Dictionary.csv',
    dataFileName: 'surveillance-with-nonconformities',
    fileExtension: 'csv',
    dfSize: '7000',
    dSize: '800',
    days: '1',
    dfLines: 30,
    dLines: 1200,
  },
  {
    file: 'Direct Review Activity',
    definitionFileName: 'Direct Review CSV Data Dictionary.csv',
    dataFileName: 'direct-reviews',
    fileExtension: 'csv',
    dfSize: '3000',
    dSize: '10',
    days: '1',
    dfLines: 20,
    dLines: 50,
  },
];
